### ISSUE TITLE
in OpenMPIR, the addClause function is huge. We need to restruct the function

### ISSUE THREAD

**Issue by yanyh15** [passlab/ompparser#22]
to breakdown into smaller functions so it is better modularized. Anjia and Yaying, please coordinate to find a way to do the refactoring. Let me know if you need me to discuss with you.

**Comment by ouankou** [comment]
It's been fixed in the merging commit https://github.com/passlab/ompparser/commit/926b41cf7849d09689146d23a2ad5eb1f9352dd0.
