### ISSUE TITLE
Clause order in ATOMIC directive

### ISSUE THREAD

**Issue by ouankou** [passlab/ompparser#35]
https://github.com/passlab/ompparser/blob/b8791487b13dfa5a8343611aed1b181ed1610e4b/src/ompparser.yy#L486

The syntax of ATOMIC directive on OpenMP 5.0 specs is that: ```#pragma amp atomic [clause11, clause12, ...] atomic-clause [clause21, clause22, ...];```.

Currently our implementation mixes the two clause portions together, which is separated by ```atomic-clause```. e.g. ```atomic hint(x) capture``` and ```atomic capture hint(x)``` would be the same.

It's still unclear whether those two portions can be mixed together or not. The implementation is kept for now. Before release, we should check it again and make the final decision.

**Comment by yanyh15** [comment]
In IR, we need to separate storing the clause in two lists, one for the clauses before atomic-clause and the other for the clauses after atomic-clause.

**Comment by XinyaoYI** [comment]
This issue has been processed.
