### ISSUE TITLE
look into the use of travis CI to check each push 

### ISSUE THREAD

**Issue by chunhualiao** [passlab/ompparser#38]
there should be some regression tests triggered to ensure new pushes won't break previous features.

**Comment by ouankou** [comment]
I tested Travis CI on my personal ompparser repository and it works. No testing script is added yet. So far after each new push, Travis CI will only make a new build and then report success or failure.
The configuration for Travis CI is [```.travis.yml```](https://github.com/ouankou/ompparser/blob/master/.travis.yml), which is added to the root folder.
There are two commits related to the initial use of Travis CI https://github.com/ouankou/ompparser/commit/c90c82b772adfcae834be7e8b2c79105d5b818f4 and https://github.com/ouankou/ompparser/commit/e7f0147ad661f7f10f5a731ab89e8ce13672cd56. The first one is a failure build and the second one is a success.

I don't have the access right to integrate Travis CI to the official ompparser repository, so I'll continue working on my own clone for now.

**Comment by yanyh15** [comment]
@ouankou Thank you. Try now to see whether you can integrate CI to the official repo

**Comment by ouankou** [comment]
> @ouankou Thank you. Try now to see whether you can integrate CI to the official repo

Yes, it works for the official repository now. Travis CI is used for the ```dev``` branch. Please check the commit https://github.com/passlab/ompparser/commit/6d63e0904fcb8d2eb20881e239cd228dbbd3d0fd for a successful build.

The next step would be to add automated tests and merge it with ```master``` branch.

**Comment by ouankou** [comment]
Compilation and grammar conflicts are checked on compilers GCC 6-9, Clang 6-10 on Ubuntu 18.04.
Please check the commits https://github.com/passlab/ompparser/commit/2027f2d380d63f4d72c6ea1b58f468e93af887e0 and https://github.com/passlab/ompparser/commit/35b5ac5490ce41136070ec38c25b13fb7142eea1.
