### ISSUE TITLE
Test on other platforms

### ISSUE THREAD

**Issue by yanyh15** [passlab/ompparser#51]
We need to test on other platform, Ubuntu, CentOS, RedHat, Windows, Mac OS X

**Comment by ouankou** [comment]
The tests can be conducted in travis CI automatically after each commit or pull request. A matrix configuration needs to be set up in ```.travis.yml```.

**Comment by ouankou** [comment]
We could migrate from Travis CI to GitHub Actions since the latter supports Linux (Ubuntu), Windows and macOS.

**Comment by ouankou** [comment]
For Windows, the compilation happens in a virtual environment of Linux. For macOS, GitHub only supports the deprecated x86 platform. Therefore, we can just focus on the Linux system.

In commit c1ab8d1bdb078aa739fb81bc25f018139cab5e88, we support the latest configurations on GitHub:
OS: Ubuntu 20.04, 22.04
GCC: 9, 10, 11
LLVM: 13, 14, 15

We can update the CI matrix whenever GitHub changes its OS support.
