### ISSUE TITLE
Questions for merging DEPEND clause

### ISSUE THREAD

**Issue by XinyaoYI** [passlab/ompparser#68]
The form of depend clause is:
depend([depend-modifier,]dependence-type : locator-list)
An instance of depend clause could be depend ( iterator(int a = 1 : 100 : 2),in : a, b, c). So if we have 2 depend clauses with same modifier and identifier, do we need to merge them? And how can we know they could be merged?
For example, can we merge "depend ( iterator( int a = 1 : 100 : 2),in : a,b,c) " and "depend ( iterator( int a = 1 : 100 : 2 ),in : d) "  to "depend ( iterator( int a = 1 : 100 : 2 ),in : a,b,c,d)"?
Also, can we merge "depend ( iterator( int a = 1 : 100 : 2),in : a,b,c)" and "depend ( iterator(double b = 0 : 50 : 2),in : a,b,c)" to "depend ( iterator(int a = 1 : 100 : 2,double b = 0 : 50 : 2),in : a,b,c)" ?
Now the depend clause cannot do the merge.

**Comment by yanyh15** [comment]
The dependent type and modifiers must the same for two clauses to merge.

**Comment by XinyaoYI** [comment]
Already solved.
