### ISSUE TITLE
Keep track of the order of clauses that are used by a directive

### ISSUE THREAD

**Issue by yanyh15** [passlab/ompparser#86]
We need to keep track of the order of the clauses that are used by a directive. The solution is to introduce a vector of clause object. Each time a clause is inserted into the clause map, it will also be pushed to the vector. So all the clause objects in the vectors are listed in the order of the clauses. 

For normalization on the fly (merging the content of a new clause to a clause object that already in the map/vector), this should be fine since we will only modify the content of the existing clause object that are in both the map and vector, we donot insert new clause object into the map. 

For normalizing two clauses whose object are already inserted into the map and vector, we need to make sure that both the map and vector are updated so the clause object whose contents are merged should be removed from both the map and vector. Currently `depend` and `mapper/map` clauses are normalized after parsing. 

After this is fixed, please also improve the ompparser unparsing so clauses will be unparsed based on their order.

**Comment by ouankou** [comment]
It's fixed by the commit https://github.com/passlab/ompparser/commit/c6febb9bb040d0978dbc97dbe9882a46dc44ce6f.
After we confirm the implementation, the unparsing module of `ompparser` will be updated accordingly.

**Comment by yanyh15** [comment]
unparsing to text is complete, dot unparsing is in-progress.
