### ISSUE TITLE
Refactor ompparser OpenMPIR.cpp code into three files: OpenMPIR.cpp, OpenMPIRToString.cpp, and OpenMPIRToDOT.cpp

### ISSUE THREAD

**Issue by yanyh15** [passlab/ompparser#94]
Refactor ompparser OpenMPIR.cpp code into three files: OpenMPIR.cpp for IR construction and normalization, OpenMPIRToString.cpp, OpenMPIRToDOT.cpp files for unparsing OpenMPIR to a string and a dot file.

**Comment by ouankou** [comment]
Fixed in commit https://github.com/passlab/ompparser/commit/1533ffa2ac014283a176a0c6f4b5eaffeb5406d4.

**Comment by yanyh15** [comment]
Merge the development to the master.

**Comment by ouankou** [comment]
Merged in commit https://github.com/passlab/ompparser/commit/85e9aac2c9cf35b606f8229f0d61b380a804c5d8.
